trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-20.04'

  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.7'
      inputs:
        versionSpec: '3.7'

    - script: pip install ansible ansible-lint
      displayName: 'Install ansible and ansible-lint'

    - script: ansible-lint -x 301 playbook.yml
      displayName: 'Run ansible lint'

    - script: |
        sudo useradd vagrant -m -G sudo
        echo vagrant:vagrant | sudo chpasswd
        sudo cat /etc/sudoers
        whoami
      displayName: 'Create vagrant user'

    - script: sudo su - vagrant -c "ansible-playbook --connection=local --inventory 127.0.0.1, --limit 127.0.0.1 playbook.yml"
      displayName: 'Run ansible'
      
- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - powershell: Install-WindowsFeature -Name Hyper-V-PowerShell
    displayName: 'Install Hyper-V Powershell module'

  - powershell: |
      mkdir C:\vagrant\
      Copy-Item "windows" -Destination "C:\vagrant\"
    displayName: 'Copy Chocolatey files to expected location'

  - powershell: ls "C:\vagrant\""
    displayName: 'ls vagrant'

  - powershell: ls "C:\vagrant\windows\""
    displayName: 'ls Chocolatey files'

  - powershell: ./windows/installChocolatey.ps1
    displayName: 'Install Chocolatey'

  - powershell: ./windows/installBoxStarter.bat
    displayName: 'Install Boxstarter'

  - powershell: |
      Import-Module C:\ProgramData\Boxstarter\Boxstarter.Chocolatey
      Install-BoxStarterPackage -PackageName "c:\vagrant\windows\BoxstarterGist.txt" -DisableReboots
    displayName: 'Run BoxStarter'