trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: '3.7'

  - script: pip install ansible-lint
    displayName: 'Install ansible-lint'

  - script: ansible-lint -x 301 playbook.yml
    displayName: 'Run ansible lint'