- hosts: all

  vars_files:
  - group_vars/all.yml
  - [ "group_vars/private.yml", "group_vars/blank.yml" ]

  pre_tasks:
    - name: update
      apt:
        upgrade: dist
      become: yes

    - name: Ansible requirements
      package:
        name:
        - git
        - python-pip
        state: present
      become: yes

    - name: Basic requirements
      package:
        name:
        - python3
        - python3-pip
        state: present
      become: yes
    
    - name: Make tools and bin dir
      file:
        path: '{{ tool_bin_dir }}'
        state: directory
        recurse: true

    - name: Add tools/bin to PATH
      lineinfile:
        path: '{{ bash_rc }}'
        line: 'PATH=$PATH:{{ tool_bin_dir }}'

    - name: Source new PATH
      shell: '. {{ bash_rc }}'
    
    - name: Configure git username
      shell: 'git config --global user.name {{ git_username }}'
      when: git_username is defined

    - name: Configure git email
      shell: 'git config --global user.email {{ git_email }}'
      when: git_email is defined

  roles:
    - powerline
    - binaryninja
    - angr
    - 010editor
    - vscode
    - keystone
    - pwndbg
    - pwntools
    - ctfrun
    - qemu-multiarch
    - cyberchef
    - jupyter
    - pia
    - chrome
    - lastpass
    - ghidra
    - i3
    - docker
    - k3s

  tasks:
    - name: get radare2
      git:
        repo: 'https://github.com/radare/radare2'
        dest: '{{ tool_dir }}radare2'

    - name: setup radare2
      shell: ./sys/install.sh
      args:
        chdir: '{{ tool_dir }}radare2'
        creates: '/usr/bin/radare2'

    - name: Install Ruby
      package:
        name:
        - ruby
        - ruby-dev
        state: present
      become: yes

    - name: Install onegadget
      gem:
        name: one_gadget
        state: latest
      become: yes

    - name: Install onegadget
      gem:
        name: seccomp-tools
        state: latest
      become: yes

    #- name: get unicorn
    #  pip:
    #    name: unicorn

    # multilib
    - name: dpkg add arch
      shell: dpkg --add-architecture i386
      become: yes

    - name: multilib
      package:
        name:
        - libc6:i386
        - libncurses5:i386
        - libstdc++6:i386
        state: present
      become: yes

    - name: Installing default tools
      package:
        name:
        - tmux
        - vim
        - gdb
        - gdb-multiarch
        - unzip
        state: present
      become: yes

    - name: Install dropbox
      apt:
        deb: https://linux.dropbox.com/packages/ubuntu/dropbox_2019.02.14_amd64.deb
      become: yes

    - name: Install dropbox service
      shell: dropbox start -i
      become: yes

    - name: Install wireshark
      package:
        name:
          - wireshark
        state: present
      become: yes

# todo: git clone my config repo.

# todo: firefox addons and set search enging to duckduckgo