- hosts: all

  vars_files:
  - group_vars/all.yml
  - [ "group_vars/private.yml", "group_vars/blank.yml" ]

  pre_tasks:
    - name: update
      apt:
        upgrade: dist
      become: yes

    - name: Ansible requirements
      package:
        name:
        - git
        - python-pip
      become: yes

    - name: Basic requirements
      package:
        name:
        - python3
        - python3-pip
      become: yes

    - name: Make tools and bin dir
      file:
        path: '{{ tool_bin_dir }}'
        state: directory
        recurse: true

    - name: Add tools/bin to PATH
      lineinfile:
        path: '{{ bash_rc }}'
        line: 'PATH=$PATH:{{ tool_bin_dir }}'
      notify: source bashrc

    - name: Configure git username
      git_config:
        name: user.name
        scope: global
        value: '{{ git_username }}'
      when: git_username is defined

    - name: Configure git email
      git_config:
        name: user.email
        scope: global
        value: '{{ git_email }}'
      when: git_email is defined

  roles:
    - powerline
    - binaryninja
    - angr
    - 010editor
    - vscode
    - keystone
    - pwndbg
    - pwntools
    - ctfrun
    - qemu-multiarch
    - cyberchef
    - jupyter
    - pia
    - brave
    - lastpass
    - ghidra
    - i3
    - docker
    - k3s

  tasks:
    - name: get radare2
      git: # noqa 401
        repo: 'https://github.com/radare/radare2'
        dest: '{{ tool_dir }}radare2'

    - name: setup radare2
      command: ./sys/install.sh
      args:
        chdir: '{{ tool_dir }}radare2'
        creates: '/usr/bin/radare2'

    - name: Install Ruby
      package:
        name:
        - ruby
        - ruby-dev
      become: yes

    - name: Install onegadget
      gem:
        name: one_gadget
      become: yes

    - name: Install seccomp-tools
      gem:
        name: seccomp-tools
      become: yes

    # multilib
    - name: Check if i386 is enabled
      shell: dpkg --print-foreign-architectures | grep i386
      register: result_i386_check
      changed_when: result_i386_check.rc == 1
      failed_when: result_i386_check.rc > 1

    - name: Enable i386 architecture
      command: dpkg --add-architecture i386
      when: result_i386_check.rc == 1
      become: yes

    - name: multilib
      package:
        name:
        - libc6:i386
        - libncurses5:i386
        - libstdc++6:i386
        state: present
      become: yes

    - name: Installing default tools
      package:
        name:
        - tmux
        - vim
        - gdb
        - gdb-multiarch
        - unzip
        state: present
      become: yes

    - name: Install dropbox
      apt:
        deb: https://linux.dropbox.com/packages/ubuntu/dropbox_2020.03.04_amd64.deb
      become: yes
      notify: Install dropbox service

    - name: Install wireshark
      package:
        name:
          - wireshark
        state: present
      become: yes

    - name: Install android RE tools
      package:
        name:
          - androguard
          - apktool
        state: present
      become: yes


# todo: git clone my config repo.

  handlers:
    - name: source bashrc
      command: '. {{ bash_rc }}'

    - name: Install dropbox service
      command: dropbox start -i
      become: yes