---
- name: Check if i386 is enabled
  shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: ansible_os_family == 'Debian'

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when:
    - ansible_os_family == 'Debian'
    - result_i386_check.rc == 1
  become: yes
  
- name: Enable multilib
  replace:
    path: /etc/pacman.conf
    regexp: '^#[multilib]\n#Include'
    replace: '[multilib]\nInclude'
  when: ansible_os_family == 'Archlinux'

- name: multilib
  package:
    name:
      "{{ packages[ansible_os_family] }}"
    state: present
  become: yes