---

- name: Get private internet access
  unarchive:
    src: '{{ pia_installer_tar }}'
    dest: '/tmp/'
    creates: "/tmp/{{ pia_installer_script }}"
    remote_src: yes

- name: Install private internet access
  shell: ./{{ pia_installer_script }}
  args:
    chdir: '/tmp/'
    creates: /opt/pia

- name: Make private internet access config dir
  file:
    path: '{{ pia_settings_dir }}'
    state: directory

- name: Configure private internet access
  template:
    src: pia-manager.json.j2
    dest: '{{ pia_settings }}'
  when: pia_username is defined