---

- name: Get private internet access
  get_url:
    url: '{{ pia_installer }}'
    dest: '/tmp/{{ pia_installer_script }}'
    checksum: '{{ pia_installer_checksum }}'

- name: Install private internet access
  command: sh {{ pia_installer_script }}
  args:
    chdir: '/tmp/'
    creates: /opt/piavpn

- name: Make private internet access config dir
  file:
    path: '{{ pia_settings_dir }}'
    state: directory

- name: Configure private internet access
  template:
    src: pia-manager.json.j2
    dest: '{{ pia_settings }}'
  when: pia_username is defined