---

# Need node role to get nodejs 10.x rather than 8.x which is the default in Ubuntu
- include_role:
    name: nodejs

- name: Install grunt
  npm:
    name: grunt-cli
    global: yes
    state: present
  become: yes

- name: get CyberChef
  git: # noqa 401
    repo: 'https://github.com/gchq/CyberChef.git'
    dest: '{{ tool_dir }}CyberChef'

- name: Install CyberChef npm dependencies
  npm:
    path: '{{ tool_dir }}CyberChef'
  notify: Deploy CyberChef
