---

- name: Install node
  package:
    name:
    - nodejs
    state: present
  become: yes

- name: Install grunt
  package:
    name:
    - node-grunt-cli
    state: present
  become: yes

- name: get CyberChef
  git: # noqa 401
    repo: 'https://github.com/gchq/CyberChef.git'
    dest: '{{ tool_dir }}CyberChef'
    force: yes

- name: Install CyberChef npm dependencies
  npm:
    path: '{{ tool_dir }}CyberChef'
  notify: Deploy CyberChef
