---

# Need node role to get nodejs 10.x rather than 8.x which is the default in Ubuntu
- include_role:
    name: nodejs

- name: get CyberChef
  git:
    repo: 'https://github.com/gchq/CyberChef.git'
    dest: '{{ tool_dir }}CyberChef'
    force: yes
    
- name: Install CyberChef npm dependencies
  npm:
    path: '{{ tool_dir }}CyberChef'
    
- name: Install grunt
  npm:
    name: grunt-cli
    global: yes
    state: latest
  become: yes
    
- name: Deploy CyberChef
  shell: grunt prod
  args:
    chdir: '{{ tool_dir }}CyberChef'
  environment:
    NODE_OPTIONS: --max_old_space_size=2048
