---

- name: Docker requirements
  apt: "pkg={{ item }} state=present"
  with_items:
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  become: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker's repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes
  become: yes

- name: Install Docker
  apt: 
    name: "{{ items }}"
    state: present
    update_cache: yes
  vars:
    items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes
  
- name: Add user to docker group
  user:
    name: "{{ vagrant_user }}"
    groups: docker
    append: yes
  become: yes