---
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# A list of users who will be added to the docker group.
docker_users: [vagrant]

# Docker Compose options.
docker_compose_path: /usr/local/bin/docker-compose
packages:
  Debian:
    - 'docker-ce'
    - 'python3-docker'
  Archlinux:
    - 'docker'
    - 'python-docker'

