---
- name: Install openjdk 11
  package:
    name:
      "{{ packages[ansible_os_family] }}"
    state: present
  become: yes

- name: Get Ghidra
  unarchive:
    src: '{{ ghidra_zip }}'
    dest: '{{ tool_dir }}'
    mode: '0755'
    creates: "{{ ghidra_run }}"
    remote_src: yes

- name: Making ghidraRun executable
  file: dest={{ ghidra_run }} mode=+x

- name: Add Ghidra to PATH
  lineinfile:
    path: '{{ bash_rc }}'
    line: 'PATH=$PATH:{{ tool_dir }}{{ ghidra_dest }}'

- name: Setup Ghidra i3 configuration.
  blockinfile:
    path: '{{ i3_config_location }}'
    marker: '# {mark} Adding Ghidra config'
    block: |
      for_window [class="Ghidra" title="CodeBrowser"] move container to workspace $ws5
      for_window [class="Ghidra" title="Ghidra"] move container to workspace $ws4
      bindsym $mod+g exec {{ ghidra_run }}
      assign [class="Ghidra"] Ghidra-CodeBrowser

- name: Setup Ghidra Desktop file
  template:
    src: ghidra.desktop.j2
    dest: '/usr/share/applications/ghidra.desktop'
    mode: '0644'
  become: yes