---
- name: add ubuntu openjdk ppa
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu"

- name: Install openjdk 11
  package:
    name:
    - openjdk-11-jdk
    - openjdk-11-jre-headless
    state: present
  become: yes
 
- name: Get Ghidra
  unarchive:
    src: '{{ ghidra_zip }}'
    dest: '{{ tool_dir }}'
    creates: "{{ tool_dir }}{{ ghidra_dest }}/ghidraRun"
    remote_src: yes

- name: Making ghidraRun executable
  file: dest={{ tool_dir }}{{ ghidra_dest }}/ghidraRun mode=+x

- name: Add Ghidra to PATH
  lineinfile:
    path: '{{ bash_rc }}'
    line: 'PATH=$PATH:{{ tool_dir }}{{ ghidra_dest }}'
