---

- name: add ubuntu openjdk ppa
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu"

- name: Install openjdk 11
  apt: "pkg={{ item }} state=present"
  with_items:
  - openjdk-11-jdk
  - openjdk-11-jre-headless
  become: yes
 
- name: Get Ghidra
  unarchive:
    src: '{{ ghidra_zip }}'
    dest: '{{ tool_dir }}ctfrun'
    creates: "{{ tool_dir }}ctfrun/ghidraRun"
    remote_src: yes

- name: Making ghidraRun executable
  file: dest={{ tool_dir }}ctfrun/ghidraRun mode=+x