---
- name: Install openjdk 11
  package:
    name:
    - openjdk-11-jdk
    - openjdk-11-jre-headless
    state: present
  become: yes

- name: Get Ghidra
  unarchive:
    src: '{{ ghidra_zip }}'
    dest: '{{ tool_dir }}'
    mode: '0755'
    creates: "{{ ghidra_run }}"
    remote_src: yes

- name: Making ghidraRun executable
  file: dest={{ ghidra_run }} mode=+x

- name: Add Ghidra to PATH
  lineinfile:
    path: '{{ bash_rc }}'
    line: 'PATH=$PATH:{{ tool_dir }}{{ ghidra_dest }}'

- name: Setup Ghidra regolith configuration.
  blockinfile:
    path: '{{ regolith_i3_config }}'
    marker: '# {mark} Adding Ghidra config'
    block: |
      for_window [class="Ghidra" title="CodeBrowser"] move container to workspace Ghidra-CodeBrowser
      for_window [class="Ghidra" title="Ghidra"] move container to workspace Ghidra-ToolChest
      bindsym $mod+g exec {{ ghidra_run }}
      assign [class="Ghidra"] Ghidra-CodeBrowser
  when: regolith_i3_config is defined

- name: Setup Ghidra regolith window configuration.
  blockinfile:
    path: '{{ home_dir }}.config/regolith/Xresources'
    marker: '! {mark} Adding regolith Ghidra config'
    block: |
      i3-wm.workspace.04.name:  "4:<span font_desc='Source Code Pro Medium 13'> Ghidra-ToolChest </span><span foreground='#2aa198'></span>"
      i3-wm.workspace.05.name:  "5:<span font_desc='Source Code Pro Medium 13'> Ghidra-CodeBrowser </span><span foreground='#2aa198'></span>"

- name: Setup Ghidra Desktop file
  template:
    src: ghidra.desktop.j2
    dest: '/usr/share/applications/ghidra.desktop'
    mode: '0644'
  become: yes