---
- name: Install i3
  package:
    name:
    - i3
    state: present
  become: yes

- name: Ensure i3 config dir is present
  file:
    path: '{{ i3_config_dir }}'
    state: directory
    recurse: true

- name: Configure i3
  template:
    src: config.j2
    dest: '{{ i3_config_location }}'

- name: Check for xrdp config
  stat:
    path: /etc/xrdp/sesman.ini
  register: xrdp_sesman

- name: Undo xrdp config for unity
  replace:
    path: /etc/xrdp/sesman.ini
    regexp: 'startubuntu'
    replace: 'startwm'
  become: yes
  when: xrdp_sesman.stat.exists

- name: Setup i3 as default window manager for sesman
  lineinfile:
    path: '{{ home_dir }}.xsession'
    line: i3
    create: yes