---
- name: Install Brave repo key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    id: 0BB75829C2D4E821
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install apt-transport-https
  package:
    name:
    - apt-transport-https
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Add Brave repository
  apt_repository:
    repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com stable main'
    filename: brave-browser-release
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Install Brave
  package:
    name:
    - brave-browser
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install Brave
  shell: |
    pikaur -Syu --noconfirm brave-bin
  when: ansible_os_family == "Archlinux"

- name: Setup Brave i3 configuration.
  blockinfile:
    path: '{{ i3_config_location }}'
    marker: '# {mark} Adding Brave config'
    block: |
      assign [class="Brave-browser"] $ws2
      bindsym $mod+b exec {{ binary[ansible_os_family] }}