---
- name: Installing socat
  package:
    name:
    - socat
    state: present
  become: yes

- name: socat ctfrunner
  git: # noqa 401
    repo: 'https://github.com/camjjack/ctfrun.git'
    dest: '{{ tool_dir }}ctfrun'

- name: link socat ctfrunner
  file:
    path: '{{ tool_bin_dir }}/ctfrun'
    state: link
    src: '{{ tool_dir }}ctfrun/ctfrun'