---
- name: Setup tmp dir for lastpass installer
  file:
    path: /tmp/lplinux
    state: directory

- name: Get lastpass
  unarchive:
    src: "https://download.cloud.lastpass.com/linux/lplinux.tar.bz2"
    dest: /tmp/lplinux
    remote_src: yes
    creates: "/tmp/lplinux/install_lastpass.sh"

- name: Install lastpass
  command: './install_lastpass.sh'
  args:
    chdir: /tmp/lplinux/
    creates: '~/.lastpass'