---
- name: Install pwntools dependencies
  package:
    name:
    - python3-dev
    - libssl-dev
    - libffi-dev
    state: present
  become: yes

- name: get pwntools
  pip:
    name: pwntools

- name: testing pwntools
  command: |
  export TERM=linux
  export TERMINFO=/etc/terminfo
  python3 -c "from pwn import pwn"