---
- name: Install pwntools dependencies
  package:
    name:
    - python2.7
    - python-dev
    - libssl-dev
    - libffi-dev
    state: present
  become: yes

- name: get pwntools
  pip:
    name: pwntools