---
- name: Install pwntools dependencies
  apt: 
    name: "{{ items }}"
    state: present
  vars:
    items:
    - python2.7
    - python-dev
    - libssl-dev
    - libffi-dev
    - build-essential
  become: yes

- name: get pwntools
  pip:
    name: pwntools