---
- name: Install pwntools dependencies
  package:
    name:
    - python3-dev
    - libssl-dev
    - libffi-dev
    state: present
  become: yes

- name: get pwntools
  command: 'pip3 install pwntools'