---
- name: Install pwntools dependencies
  package:
    name:
      "{{ packages[ansible_os_family] }}"
    state: present
  become: yes

- name: get pwntools
  pip:
    name: pwntools
  register: pwntools

- name: testing pwntools
  command: python3 -c "from pwn import *"
  environment:
    TERM: "linux"
    TERMINFO: "/etc/terminfo"
  when: pwntools.changed