---
- name: Install pwntools dependencies
  package:
    name:
    - python3-dev
    - libssl-dev
    - libffi-dev
    state: present
  become: yes

- name: get pwntools
  pip:
    name: pwntools

- name: Remove old version of six
  file:
    path: /home/vagrant/.local/lib/python3.8/site-packages/six.py
    state: absent

- name: testing pwntools
  command: python3 -c "from pwn import *"
  environment:
    TERM: "linux"
    TERMINFO: "/etc/terminfo"