---
- name: Install angr dependencies
  apt: "pkg={{ item }} state=present"
  with_items:
  - python3-dev
  - libffi-dev
  - build-essential
  - libffi-dev
  - build-essential
  - virtualenvwrapper
  become: yes

- name: get angr
  pip:
    name: angr
  become: yes
