---
- name: Install angr dependencies
  package:
    name:
    - python3-dev
    - build-essential
    - libffi-dev
    - python3-venv
    - python3-pkg-resources
    - virtualenvwrapper
    state: present
  become: yes

- name: Install angr
  pip:
    name: angr