---
- name: Install angr dependencies
  package:
    name:
      "{{ packages[ansible_os_family] }}"
    state: present
  become: yes

- name: Create the angr virtualenv
  command:
    cmd: python3 -m venv {{ home_dir }}/angrenv
    creates: "{{ home_dir }}/angrenv"

- name: Install angr
  shell: "{{ home_dir }}/angrenv/bin/pip3 install angr"