---
- name: Install angr dependencies
  package:
    name:
    - python3-dev
    - libffi-dev
    - build-essential
    - libffi-dev
    - build-essential
    - virtualenvwrapper
    state: present
  become: yes

- name: get angr
  pip:
    name: angr
  become: yes
