---
# QEMU with MIPS/ARM - http://reverseengineering.stackexchange.com/questions/8829/cross-debugging-for-mips-elf-with-qemu-toolchain

- name: Install qemu architectures
  package:
    name:
    - qemu
    - qemu-user
    - qemu-user-static
    - 'binfmt*'
    - libc6-armhf-armel-cross
    - libc6-mipsel-cross
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install qemu architectures
  shell: |
    pikaur -Sy --noconfirm qemu-user-static-bin binfmt-qemu-static
  when: ansible_os_family == "Archlinux"

- name: Make qemu binfmt dir
  file:
    path: '/etc/qemu-binfmt'
    state: directory
    mode: '0644'
  become: yes
  when: ansible_os_family == "Debian"

- name: link qemu MIPS
  file:
    path: /etc/qemu-binfmt/mipsel
    state: link
    src: /usr/mipsel-linux-gnu
  become: yes
  when: ansible_os_family == "Debian"

- name: link qemu ARM
  file:
    path: /etc/qemu-binfmt/arm
    state: link
    src: /usr/arm-linux-gnueabihf
  become: yes
  when: ansible_os_family == "Debian"