---
- name: Get 010Editor
  unarchive:
    src: "https://www.sweetscape.com/download/010EditorLinux{{ architecture }}Installer.tar.gz"
    dest: /tmp/
    remote_src: yes
    mode: '0755'
    creates: "/tmp/010EditorLinux{{ architecture }}Installer"

- name: Install 010Editor
  command: './010EditorLinux{{ architecture }}Installer --mode silent --prefix {{ tool_dir }}010editor/'
  args:
    chdir: /tmp/
    creates: '{{ tool_dir }}010editor/'

- name: Add 010editor to PATH
  lineinfile:
    path: '{{ bash_rc }}'
    line: 'PATH=$PATH:{{ tool_dir }}/010editor/'
    state: present
